from report_helpers import *

p('LAB EXERCISE: 2','title')
p('Intelligent Question Answering and Chatbot System','title')
table([['Student Name','Aditi S Yaranal','USN','1GA23AI003'],['Semester / Department','7th Semester / AIML','Date',DATE],['Institution','Global Academy of Technology','Course','AML23702']],[105,195,45,WIDTH-345],False)
h('Aim / Objective')
p('To design and implement a question answering and chatbot system combining information-retrieval-based factoid QA, structured knowledge-based QA and simple dialogue management, and evaluate its answers and conversational context.')
h('Expected Outcomes Addressed')
for x in ['Retrieve relevant documents and evidence sentences using TF-IDF and cosine similarity.','Extract factoid answer spans such as people, locations and dates.','Identify disease entities and relations, then query a structured CSV knowledge source.','Maintain a conversation frame and resolve simple pronoun follow-ups.','Evaluate exact match, token F1, expected-fact coverage, intent and entity-state correctness.']:bullet(x)
h('Tools & Technologies Used')
table([['Category','Tool','Purpose'],['Backend','Python 3.12 / FastAPI 0.115','Local API and validation'],['NLP / retrieval','scikit-learn 1.5.2 / regular expressions','TF-IDF, cosine ranking and span extraction'],['Frontend','React 18 / Vite 5 / Tailwind CSS 3','Interactive QA, chat and evaluation'],['Data','Text, CSV and JSON','Corpus, structured facts and test questions'],['Verification','unittest / FastAPI TestClient','Regression and API checks']],[90,180,WIDTH-270])
page();h('Dataset / Corpus Description')
p('The repository supplies eight short English text documents spanning science, history, geography, technology and education. These are a small educational corpus; they are not a continuously updated external knowledge source. Text is split into sentences and indexed with English stop-word removal.')
p('The healthcare CSV has 15 disease entities, aliases and six relations: category, symptoms, causes, treatment, specialist and prevention. CSV rows are loaded into an entity-to-relations dictionary. This demonstrates structured querying without requiring a database server.')
p('Healthcare values are educational sample data without per-row medical provenance. Responses explicitly identify them as sample KB entries. They must not be used for diagnosis or treatment advice.')
table([['Evaluation partition','Size','Reference format'],['IR questions','17','Full expected answer span'],['KB questions','15','Expected fact phrase within a longer stored value'],['Dialogue sequence','7 turns','Intent on all turns; entity state on four turns']],[150,65,WIDTH-215])
h('System Architecture / Pipeline Design')
diagram(['Question\nReact interface','FastAPI\nRequest routing','IR / structured KB\nAnswer + evidence'])
diagram(['Chat message\nSession identifier','Intent + entity frame\nPronoun resolution','KB then IR\nUpdate conversation'])
p('IR pipeline: normalize and expand common abbreviations; rank documents with TF-IDF; rank candidate sentences; apply event-sensitive begin/end ranking; extract an answer; return its actual evidence document. The displayed confidence is a heuristic score, not a calibrated probability.')
p('Knowledge pipeline: longest alias with word boundaries; relation keyword matching; entity/relation lookup; template-based answer. Unsupported relations return no structured answer rather than an unrelated category.')
page();h('Backend Implementation')
sub('6.1 Approach / Algorithm')
p('IR extraction uses WH-question type, date expressions, proper-name candidates and grammatical patterns. Agent phrases preserve compound founders such as Bill Gates and Paul Allen; role questions can extract the sentence subject. Evidence remains inspectable.')
p('The dialogue frame stores current_entity, previous_question, previous_answer, detected_intent and the last six message entries. Greetings, help and goodbye have explicit handling. A complete goodbye expression is required, so a question containing the word end remains a question. Pronouns can reuse a known healthcare entity; an unrelated IR topic clears that entity.')
sub('6.2 Key Code Snippets')
code('if re.search(r"(?<!\\w)" + re.escape(alias) + r"(?!\\w)",\n             question.lower()):\n    return canonical')
p('Word boundaries avoid matching the flu alias inside influence.','small')
code('best_doc = next(d for d in retrieved_docs\n                if d["doc_id"] == candidate_sentences[0]["doc_id"])\nbest_sentence_text = candidate_sentences[0]["text"]')
p('The answer source follows the selected sentence, even if it comes from a document other than the top-ranked passage.','small')
code('resolved_message = self.resolve_coreference(message, session)\nkb_result = self.knowledge_service.query(\n    resolved_message, context_entity=None)')
p('Context is introduced through an explicit pronoun resolution step, avoiding unconditional reuse of the previous entity.')
h('Frontend / UI Implementation')
sub('7.1 Framework Choice')
p('React and React Router provide five pages: Home, IR-Based QA, Knowledge-Based QA, Chat and Evaluation. Vite proxies local API calls to FastAPI; Tailwind provides the existing dark interface.')
sub('7.2 Interface Features')
p('The interface exposes retrieved evidence, pipeline stages, structured records, source badges, chat reset and live evaluation tables. A per-tab session identifier separates conversations. Reset is disabled while an answer is loading.')
for filename, title, caption in [
 ('ir-qa.png', 'Website Screenshots - IR-Based QA', 'Figure 1. Live factoid answer: Guido van Rossum, with its source document and confidence display.'),
 ('chat.png', 'Website Screenshots - Dialogue', 'Figure 2. A healthcare KB query followed by a contextual question using its. The source badges identify the structured knowledge base.')]:
 page();h(title)
 from PIL import Image as PILImage
 shot=ROOT/'output'/filename
 iw,ih=PILImage.open(shot).size
 scale=min(WIDTH/iw,590/ih)
 story.append(Image(str(shot),width=iw*scale,height=ih*scale))
 p(caption,'small')
 p('Captured from the running website on '+DATE+'.','small')
page();h('Sample Input & Output')
table([['Input','Observed output / behavior'],['Who founded Microsoft?','Bill Gates and Paul Allen'],['Who is the CEO of Microsoft?','Satya Nadella (from the supplied static document)'],['When did World War II end in Europe?','May 8, 1945'],['Who created Python?','Guido van Rossum'],['What are the symptoms of Diabetes?','Returns the symptoms value from the sample CSV; current entity becomes Diabetes.'],['What is its treatment?','Resolves its to Diabetes and queries treatment.'],['Who created Python? (after Diabetes)','Routes to document retrieval and clears the healthcare entity.']],[210,WIDTH-210])
h('Results (Deliverable-Specific Outputs)')
for x in ['Working prototype: FastAPI backend and React interface, fully local with no LLM/API key requirement.','Sample QA set: backend/data/evaluation_dataset.json; 17 IR questions, 15 KB questions and seven dialogue turns.','Dialogue frame and flow: documented in docs/dialogue_flow.md.','Evaluation summary: saved before/after JSON, regression results and the live Evaluation page.','Submission: source code, reproducible setup, this PDF and the report builder.']:bullet(x)
h('Evaluation / Analysis')
table([['Measure','Before review','After review'],['IR exact match (17)','82.4% (14/17)','100% (17/17)'],['Mean token F1 (17)','85.7%','100%'],['KB expected-fact coverage (15)','100% (original metric)','100% (complete phrase required)'],['Dialogue intent (7)','100%','100%'],['Dialogue entity state (4)','Not evaluated','100%'],['Regression / API checks','Not supplied','9 / 9 passed']],[190,140,WIDTH-330])
p('These are development-set results, including cases used to guide fixes. They do not establish general accuracy. The KB score measures expected phrase coverage, not exact match of the entire answer or medical validity. No held-out benchmark or statistical generalization claim is made.')
page();h('Evaluation / Analysis (continued)')
im=ROOT/'output/evaluation.png'
if im.exists():
 from PIL import Image as PILImage
 iw,ih=PILImage.open(im).size
 scale=min(WIDTH/iw,590/ih)
 story.append(Image(str(im),width=iw*scale,height=ih*scale))
 p('Figure 3. Live evaluation page captured on '+DATE+'.','small')
h('Challenges Faced & Solutions')
p('Incorrect span selection was corrected using agent/subject patterns and event-sensitive ranking. Source attribution now follows the evidence sentence. Alias boundaries prevent accidental disease matches, and unsupported relations no longer default silently to a category. Chat topic changes no longer inherit the previous healthcare entity.')
page();h('Conclusion')
p('The prototype satisfies the three core implementation areas of Exercise 2: IR-based factoid QA, structured knowledge QA and basic dialogue management. It presents evidence and measures results transparently. Rule-based extraction remains sensitive to wording, multi-date sentences and unsupported questions; future work should add held-out evaluation, stronger relation parsing and sourced knowledge data.')
p('The frontend production build passed. Compatible dependency updates were applied, but npm audit still reports 11 dependency advisories (five moderate, six high). Resolving the remaining reports requires a separately tested major-version migration. Use the application as a local academic demo; production hardening is outside this exercise.')
h('Project Repository (GitHub Link)')
table([['Field','Submission details'],['Repository','https://github.com/Aditisy/qa-chatbot-system'],['Branch','main'],['Student / USN','Aditi S Yaranal / 1GA23AI003'],['Submission date',DATE]],[135,WIDTH-135])
sub('Reproduction Commands (Windows PowerShell)')
code('py -3.12 -m venv .venv\n.\\.venv\\Scripts\\python -m pip install -r backend/requirements.txt\n.\\.venv\\Scripts\\python -m uvicorn app.main:app --app-dir backend\n# In a second terminal:\ncd frontend\nnpm ci\nnpm run dev -- --host 127.0.0.1')
p('Open http://127.0.0.1:5173. Run tests from the repository root after installing backend/requirements-dev.txt and setting PYTHONPATH to backend. Runtime files and dependencies are excluded from Git.')
h('References')
for x in ['Lab Exercise with Rubrics (2).pdf: Exercise 2 objective, outcomes, deliverables and assessment rubric.','ANLP_Lab1_report013.pdf: supplied report format; section structure adapted to Exercise 2, matching the Lab 3 submission style.','Repository source, corpus and evaluation_dataset.json: https://github.com/Aditisy/qa-chatbot-system','TF-IDF and cosine similarity are implemented with scikit-learn; the application uses FastAPI, React, Vite and Tailwind CSS.']:bullet(x)
page();p('ADVANCE NLP (AML23702)','title');p('LAB EXERCISE EVALUATION SHEET','title')
table([['Student Name','Aditi S Yaranal'],['USN','1GA23AI003'],['Lab Exercise No.','2'],['Experiment Title','Intelligent Question Answering and Chatbot System'],['Semester / Department','7th Semester / AIML'],['Institution','Global Academy of Technology']],[145,WIDTH-145],False)
p('Marks Awarded','title')
criteria=[('Problem Understanding & Scope','5'),('Pipeline Design & Methodology','10'),('Implementation Correctness','10'),('Use of NLP Tools / Models','5'),('Output Quality / Task Performance','10'),('Analysis & Interpretation','5'),('Documentation & Deliverables','2.5'),('Presentation & Reproducibility','2.5')]
table([['Sl. No.','Evaluation Criteria','Max Marks','Marks Obtained']]+[[str(i),c,m,''] for i,(c,m) in enumerate(criteria,1)]+[['','Total','50','']],[40,WIDTH-175,60,75])
sub('Overall Comments')
story.append(Table([[''],[''],['']],colWidths=[WIDTH],rowHeights=[22]*3,style=TableStyle([('LINEBELOW',(0,0),(-1,-1),.4,GRAY)])))
story.append(Spacer(1,22));table([['Date of Submission',DATE],['Signature of Faculty','']],[145,WIDTH-145],False)
SimpleDocTemplate(str(TARGET),pagesize=A4,leftMargin=48,rightMargin=48,topMargin=54,bottomMargin=42,title='1GA23AI003 - Exercise 2 - QA Chatbot',author='Aditi S Yaranal').build(story,canvasmaker=NumberedCanvas)
(ROOT/'REPORT.md').write_text('\n'.join(line.rstrip() for line in md).rstrip() + '\n',encoding='utf-8')
print(TARGET)
